### ISSUE TITLE
Website enhancements

### ISSUE THREAD

**Issue by Vector-S** [AlphaTac-AI/AlphaTac-Frontend#7]
- [ ] Name AlphaTac AI as home page

- [ ] Name Dota 2 Analytics as product

- [ ] Add an about page

**Comment by PeiShang** [comment]
[brunch.pdf](https://github.com/AlphaTac/AlphaTac-Frontend/files/2020036/brunch.pdf)

**Comment by PeiShang** [comment]
### main page
![image](https://user-images.githubusercontent.com/37992256/40275895-41df9452-5c2f-11e8-9c4b-574e8df9128b.png)
### about page
![image](https://user-images.githubusercontent.com/37992256/40275898-4f850d26-5c2f-11e8-95e2-8208b4e0621b.png)
### team page
![image](https://user-images.githubusercontent.com/37992256/40275899-5df4263a-5c2f-11e8-95d7-b7af436b3a4a.png)
### product page1
![image](https://user-images.githubusercontent.com/37992256/40275903-6b607300-5c2f-11e8-97e7-961767f0185d.png)
### product page2(optinal)
![image](https://user-images.githubusercontent.com/37992256/40275906-7ac2f76e-5c2f-11e8-8d13-530537ffc8ff.png)
